name: Pull Request Workflow

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m --enable exportloopref
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Go Mod Download
        run: go mod download

      - name: Go Build amd64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o k8s-parallel-exec-amd64

      - name: Go Build arm64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o k8s-parallel-exec-arm64
