name: Release Workflow

on:
  release:
    types:
      - published

env:
  GO_VERSION: 1.20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Go Lint
      uses: golangci/golangci-lint-action@v3.4.0
      with:
        args: --timeout=5m --enable exportloopref
        skip-pkg-cache: true
        skip-build-cache: true
        skip-go-installation: true

    - name: Build
      run: go build -o k8s-parallel-exec

    - name: Publish k8s-parallel-exec to assets
      uses: skx/github-action-publish-binaries@release-2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: './k8s-parallel-exec'
