name: Release Workflow

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Go Lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout=5m --enable exportloopref
        skip-pkg-cache: true
        skip-build-cache: true

    - name: Go Mod Download
      run: go mod download

    - name: Go Build amd64
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o k8s-parallel-exec-amd64

    - name: Go Build arm64
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o k8s-parallel-exec-arm64

    - name: Publish k8s-parallel-exec to amd64 assets
      uses: skx/github-action-publish-binaries@release-2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: './k8s-parallel-exec-amd64'

    - name: Publish k8s-parallel-exec to arm64 assets
      uses: skx/github-action-publish-binaries@release-2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: './k8s-parallel-exec-arm64'
